"""English copy for the browser edition. The Japanese source stays authoritative."""

BODY = {
    '複数の動画をつなぎ、カットや速度を調整して歌詞の動きを重ねられます。': 'Join multiple videos, edit cuts and speed, and add animated lyrics.',
    '動画を追加／再読み込み': 'Add / reimport videos',
    '動画をすべて外す': 'Remove all videos',
    '歌詞の開始・終了は下の行リストで調整。編集した動画の長さで書き出します。動画は端末内で処理されます。': 'Adjust lyric start and end times in the line list below. Export uses the edited video duration. Video processing stays on your device.',
    '動画クリップ（選んで編集）': 'Video clips (select to edit)',
    'クリップを選択してください': 'Select a clip',
    '選択クリップの編集': 'Edit selected clip',
    '現在の再生位置でクリップを2つに分ける': 'Split the clip at the current playback position',
    '再生位置で分割': 'Split at playhead',
    '選択中のクリップを複製する': 'Duplicate the selected clip',
    '選択クリップを1つ前へ移動': 'Move the selected clip one place earlier',
    '選択クリップを1つ後ろへ移動': 'Move the selected clip one place later',
    'ひとつ前へ移動': 'Move one place earlier',
    'ひとつ後ろへ移動': 'Move one place later',
    '← 前へ': '← Earlier', '後ろへ →': 'Later →',
    '選択中のクリップを削除する': 'Delete the selected clip',
    '動画編集の履歴': 'Video edit history',
    '動画編集を元に戻す': 'Undo video edit',
    '動画編集をやり直す': 'Redo video edit',
    '↶ 戻す': '↶ Undo', '↷ やり直す': '↷ Redo',
    '元動画の開始（秒）': 'Source start (s)',
    '元動画の終了（秒）': 'Source end (s)',
    'プレビューの再生位置を切り出しの開始にする': 'Set the source start from the preview playback position',
    'プレビューの再生位置を切り出しの終了にする': 'Set the source end from the preview playback position',
    '再生位置を開始に': 'Set start here', '再生位置を終了に': 'Set end here',
    '再生速度': 'Playback speed', '1×（通常）': '1× (normal)',
    'フェードイン（秒）': 'Fade in (s)', 'フェードアウト（秒）': 'Fade out (s)',
    'クリップの音量': 'Clip volume', '左右反転': 'Flip horizontally',
    'クリップに適用': 'Apply to clip',
    '歌詞の時刻は、編集後の動画全体のタイムラインに対応します。カットや速度変更後は歌詞のタイミングも確認してください。速度を変えると元動画の音声の高さも変わります。': 'Lyric times refer to the final edited timeline. Check them after changing cuts or speed. Source audio changes pitch with playback speed.',
    '歌詞タイムライン（クリックで移動）': 'Lyric timeline (click to seek)',
    '動画編集': 'Video editor', '複製': 'Duplicate', '削除': 'Delete',
    'MVに文字を重ねる': 'Add lyrics to an MV',
    '動画を読み込み、歌詞の動きをそのまま重ねて書き出せます。': 'Import a video, add animated lyrics and export the composite.',
    'MV動画を読み込む': 'Import MV video', '動画を外す': 'Remove video',
    '動画なし · MP4 / WebM など': 'No video · MP4, WebM and more',
    '映像の収め方': 'Video fit', '全体を収める': 'Fit whole video', '画面いっぱい': 'Fill frame',
    '使用する音声': 'Audio source', '元動画の音声': 'Video audio',
    '別に読み込んだ曲': 'Imported audio', '音声なし': 'Mute',
    '文字の配置プリセット': 'Text placement presets',
    '中央': 'Center', '下に配置': 'Lower', '上に配置': 'Upper',
    '文字の大きさ': 'Text scale', '左右の位置': 'Horizontal position',
    '上下の位置': 'Vertical position', '映像を暗くする': 'Dim video',
    '文字に影を付ける': 'Text shadow',
    '歌詞の開始・終了は下の行リストで調整。MVの長さで書き出します。動画は端末内で処理されます。': 'Adjust lyric start and end times in the line list below. Export uses the MV duration. Video processing stays on your device.',
    '歌詞の言語': 'Lyrics language', '<option value="auto">自動判定</option>': '<option value="auto">Auto-detect</option>',
    '<button id="btnAddFont">追加</button>': '<button id="btnAddFont">Add</button>',
    '曲名': 'Song title', '自動': 'Auto',
    '曲名（タイトルカード・HUDに表示）': 'Song title (shown on title cards and HUD)',
    'アーティスト': 'Artist', '表示モード': 'Editor mode',
    'おまかせボタン中心のシンプルな画面': 'A simple workspace focused on automatic creation',
    'すべての設定を表示': 'Show all settings',
    '保存したプロジェクト(.json)を開く': 'Open a saved project (.json)',
    'プロジェクトを .json で保存': 'Save project as .json',
    'After Effects パネル用の構成データを書き出す': 'Export project data for the After Effects panel',
    '出力物の権利とライセンス': 'Rights and licenses for your exports',
    '歌詞とタイミング': 'Lyrics and timing', 'スタイルと書き出し': 'Style and export',
    '歌詞（1行 = 1フレーズ）': 'Lyrics (one phrase per line)',
    '1行が1フレーズ。空行は少し間を空けます': 'One phrase per line. A blank line adds a short pause.',
    '夜明けの色を/覚えてる': 'I remember/the dawn',
    'でカットの切れ目を指定': 'marks a cut boundary',
    '… 強調（大きく・インパクト寄りの演出）': '… emphasis (larger, stronger effects)',
    '… フラッシュと揺れを入れる': '… adds a flash and shake',
    '… 注釈レイアウトの小さな文字': '… smaller text in annotation layouts',
    '… LRC のタイムスタンプをそのまま使用': '… uses an LRC timestamp',
    'で始まる行 … コメント（無視）': 'starts a comment (ignored)',
    '行末の': 'A trailing', '透明': 'transparent', '歌詞|ruby or note': 'lyrics|reading or note',
    '歌詞': 'Lyrics', '曲とタイミング': 'Audio and timing',
    '曲なし（読み込むと拍を検出してカットを合わせます）': 'No audio. Import a song to detect beats and align cuts.',
    'mp3 / wav / m4a など': 'MP3, WAV, M4A and more',
    '曲を読み込む': 'Import audio', '曲を再生しながら各行の頭でタップ': 'Tap at the start of each line while the song plays',
    'タップで同期': 'Tap to sync', '開始(秒)': 'Start (s)', '行の長さ': 'Line duration',
    '拍にスナップ': 'Snap to beat', '手動タイミングを消す': 'Clear manual timing',
    '曲に合わせて、各行が始まる瞬間に': 'Press', 'かボタンを押してください。': 'or the button as each line starts.',
    '次:': 'Next:', '終了する': 'Finish', '行とカット': 'Lines and cuts',
    '再生位置': 'Playback position', 'タイムライン（クリックで移動）': 'Timeline (click to seek)',
    '前の案に戻る': 'Previous variation', '次の案へ進む': 'Next variation',
    '設定はそのままで構成だけ再抽選（ロックした行は維持）': 'Shuffle the arrangement, keeping locked lines',
    'スタイル・雰囲気・演出・配色をまるごとランダムに（キー R）': 'Randomize style, mood, effects and colors (R)',
    '押すたびに、スタイル・雰囲気・動き・配色・構成がまるごと変わります。キーボードの': 'Each click changes the style, mood, motion, colors and arrangement. Press',
    'でも実行できます。': 'to do the same.',
    '最初の公開版のあとに追加した約350の演出・配色セット12・書体6も、おまかせやシャッフルの候補にします（オフのときは最初の公開版の演出だけ）': 'Include about 350 more effects, 12 styles and 6 fonts in random picks. Off uses the original set.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィック。オフにすると、おまかせやシャッフルで選ばれません': 'Include Japanese motifs such as lanterns, postcards, shoji, fans, family crests, waves and cherry blossoms in random picks.',
    '「追加」印の手法・スタイル・書体。オフのときは、おまかせやシャッフルで最初の公開版の演出だけを使います': 'Include techniques, styles and fonts marked New in automatic picks.',
    '「和」印の手法とスタイル。オフにすると、おまかせやシャッフルでは選ばれません（追加分の判定のあとに適用。行ごとに手動で指定した場合は使えます）': 'Include techniques and styles marked JP in automatic picks. Manual selections remain available.',
    '追加分の演出も使う': 'Include new effects', '和風の演出も使う': 'Include Japanese motifs',
    'スタイルだけ別のものに': 'Change the style only', 'アクセント・ズレ色A/Bをランダムに': 'Randomize accent and offset colors',
    '動き・グリッチ・使う手法の雰囲気だけ': 'Change motion, glitch and technique mood',
    'レイアウトと動きの組み合わせだけ': 'Change the arrangement and motion only',
    '画面比': 'Aspect ratio', '解像度': 'Resolution', '画質': 'Quality',
    '通常（スタイルの背景）': 'Style background', 'グリーンバック（合成用）': 'Green screen (compositing)',
    'ブラックバック（合成用）': 'Black background (compositing)',
    'MP4 を書き出す': 'Export MP4', '書き出した動画の権利について': 'Rights to exported videos',
    'フォントの役割': 'Font roles', 'PCのフォント名（例: 游明朝）': 'Installed font name (e.g. Arial)',
    'フォントファイル（.ttf/.otf）': 'Font file (.ttf/.otf)',
    'アクセント・ズレ色': 'Accent and offset colors',
    '全シーンに適用。背景に合わせて明るさを自動調整します': 'Applies to every scene. Brightness adapts to the background.',
    '自分の色で上書き': 'Use custom colors', 'ランダムに配色': 'Randomize palette',
    '背景・文字色': 'Background and text colors', 'メインの背景と文字を自分の色にする': 'Use custom background and text colors',
    '動きを何枚/秒で描くか（出力fpsとは別）': 'Motion drawings per second (independent of export fps)',
    'フル（出力fpsのまま）': 'Full (export fps)', '2コマ打ち（12枚/秒）': 'On twos (12 drawings/s)',
    '3コマ打ち（8枚/秒）': 'On threes (8 drawings/s)',
    'スタイル次第': 'Auto (by style)', '常に表示': 'Always show', '表示しない': 'Hide',
    '同じシードなら同じ構成になります。行ごとの「再抽選」「ロック」は左の行リストから。': 'The same seed produces the same arrangement. Reroll or lock individual lines in the list on the left.',
    '手法を名前で絞り込み': 'Filter techniques by name',
    'グリーンバック／ブラックバックにすると、白い文字と演出だけを単色の背景の上に描きます（背景の模様・紙の質感・粒子・周辺減光は入りません）。プレビューにもそのまま反映されます。グリーンバックは動画編集ソフトのクロマキーで、ブラックバックは「スクリーン」合成や輝度キーで抜いて、別の映像の上に重ねられます。': 'Green screen and black background render white text and effects over a solid color, without background patterns, paper texture, particles or vignette. The preview shows the export. Use a chroma key for green or Screen blending / a luma key for black to composite over footage.',
    '曲を動画に含める': 'Include audio in video', '連番PNG（ZIP）': 'PNG sequence (ZIP)',
    '透過PNG（ZIP・背景なし）': 'Transparent PNG (ZIP)',
    '書き出した動画・画像の権利とライセンスについて': 'Rights and licenses for exported videos and images',
    '書き出しはこのブラウザの中で行われます（Chrome / Edge 推奨）。': 'Export runs in your browser (Chrome or Edge recommended).',
    'このツールで作った': 'You own the', '動画や画像（出力物）の権利は、作った人': 'videos and images you create',
    'に帰属します。': '.', '※ 使った歌詞や曲の権利は、それぞれの権利者に帰属します。': 'Lyrics and music remain the property of their respective rights holders.',
    'ツール本体は': 'The tool is released under the', 'ライセンス': 'license',
    'で公開しています。詳細なライセンスはこちら：': '. See the license at:',
    '入力した歌詞や曲は、このブラウザの中だけで処理され、サーバーには送信されません。': 'Your lyrics and audio are processed in this browser and are not sent to a server.',
    '使用しているオープンソース': 'Open source software', 'MP4 書き出し：': 'MP4 export: ',
    'フォント：': 'Fonts: ', '配布の各書体': 'typefaces', '閉じる': 'Close',
    'かんたん': 'Simple', '詳細': 'Advanced', '開く': 'Open', '保存': 'Save',
    'AE用に書き出し': 'Export for AE', '利用について': 'About / rights',
    '記法': 'Syntax', 'プレビュー': 'Preview', '再生': 'Play', 'ループ': 'Loop',
    '前の案': 'Previous', '次の案': 'Next', 'シャッフル': 'Shuffle', 'おまかせで作る': 'Create a variation',
    'おまかせ': 'Randomize', 'いまの案': 'Current variation', 'ここだけ変える': 'Change one thing',
    'スタイル': 'Style', '配色': 'Palette', '雰囲気': 'Mood', '構成': 'Arrangement',
    '書き出し': 'Export', '縦': 'portrait', '背景': 'Background',
    '追加': 'New', '和': 'JP', '演出': 'Effects', '手法': 'Techniques',
    'コマ打ち': 'Frame stepping', 'フラッシュ': 'Flash', 'シード': 'Seed', '新しいシード': 'New seed',
    '標準': 'Standard', '最高': 'Maximum', '高': 'High', '中止': 'Cancel',
}

UI = {
    '未読み込みの動画があります。元ファイルを追加してから書き出してください。': 'Some videos are missing. Reimport the source files before exporting.',
    '未読み込みの動画があります。元ファイルを追加してから再生してください。': 'Some videos are missing. Reimport the source files before playing.',
    '動画なし · 複数の動画を追加できます': 'No video · Add multiple videos',
    '元ファイルを追加して再接続してください: ': 'Reimport source files to reconnect: ',
    '音声を読み取れない動画があります。そのクリップの音量を0%にするか、別の曲を選んでください。': 'Some video audio could not be read. Set those clips to 0% volume or choose imported audio.',
    '動画を追加して編集を始めてください': 'Add videos to start editing',
    '未読み込み: ': 'Missing: ',
    '未読み込み ${missing.length}本': '${missing.length} missing',
    'クリップ · ': ' clips · ',
    '開始と終了を動画の範囲内で指定してください。終了は開始より後にしてください。': 'Keep start and end within the source video. End must be later than start.',
    '選択したクリップの中へ再生位置を移動してください。': 'Move the playhead inside the selected clip.',
    '動画を読み込み中: ': 'Loading video: ',
    '動画を再生できません。元ファイルを確認してください。': 'Could not play the video. Check the source file.',
    '（元動画）': ' (source video)',
    '再読み込みが必要: ': 'Reimport needed: ',
    '動画なし · MP4 / WebM など': 'No video · MP4, WebM and more',
    '保存した設定を使うには、同じMV動画を読み込み直してください。': 'Reimport the same MV video to use the saved settings.',
    '元動画の音声を読み取れませんでした。書き出しには別の曲を読み込むか「音声なし」を選んでください。': 'Could not read the video audio. Import a separate audio file or select Mute before exporting.',
    '「曲を読み込む」で使用する音声を選んでください。': 'Use Import audio to choose an audio file.',
    '動画の終了より後に始まる歌詞があります。開始時刻を調整してください。': 'Some lyrics start after the video ends. Adjust their start times.',
    'MV動画を読み込み中…': 'Loading MV video…',
    '映像を読み込みました。元動画の音声を解析中…': 'Video loaded. Analyzing the video audio…',
    '動画を再生できません。別の形式で読み込み直してください。': 'Could not play the video. Reimport it in another format.',
    'MV動画を読み込めませんでした。': 'Could not import the MV video.',
    '動画を再生できませんでした。再生ボタンをもう一度押してください。': 'Could not play the video. Press Play again.',
    '${i + 1}行目の終了秒': 'Line ${i + 1} end time (s)',
    '今の再生位置を開始にする': 'Set start to current playback position',
    '開始を現在位置へ': 'Start here', '終了を自動に戻す': 'Reset end to automatic',
    '<label>終了 ': '<label>End ',
    '保存したMV動画をもう一度読み込んでください。': 'Reimport the MV video used by this project.',
    '元動画の音声を読み取れません。「別に読み込んだ曲」を使うか「音声なし」を選んでください。': 'Could not read the video audio. Select Imported audio and import an audio file, or select Mute.',
    '使用する曲を読み込んでください。': 'Import the audio file you want to use.',
    '動画・音声の読み込みが終わってから書き出してください。': 'Wait for the video and audio to finish loading before exporting.',
    '曲を使う場合は、曲も読み込み直してください。': 'Reimport the audio file if you want to use it.',
    '歌詞の言語：自動判定 → ': 'Lyrics language: auto-detect → ', '歌詞の言語：': 'Lyrics language: ',
    '${S.plan.cuts.length}カット': '${S.plan.cuts.length} cuts',
    '${i + 1}行目の開始秒': 'Line ${i + 1} start time (s)',
    'スタイル': 'Style', '雰囲気': 'Mood', '配色': 'Palette',
    '構成': 'Arrangement', '演出': 'Effects', '種': ' types',
    'のフォント': ' font',
    'で書き出します（': 'at (', '）。': '). ',
    '最初の公開版のあとに追加': 'Added after the original release', '和風の演出': 'Japanese motifs',
    'フォントを読み込み中…': 'Loading fonts…', '一時停止': 'Pause', '再生': 'Play',
    'この位置にカットはありません': 'No cut at this position',
    'スタイルの既定': 'Style default', '見出し書体': 'Display font',
    '見出し': 'Display', '明朝枠': 'Serif frame', '小さな文字': 'Small text',
    '背景の切替': 'Background changes', '動きの強さ': 'Motion strength',
    'カットの細かさ': 'Cut density', '装飾の量': 'Decoration amount',
    '文字の加工': 'Text treatments', '画面効果': 'Screen effects',
    'カット間のつなぎ': 'Transitions', 'レイアウト': 'Layout', '登場': 'Entrance',
    '保持': 'Hold', '退場': 'Exit', '装飾': 'Decoration', '加工': 'Treatment',
    'カメラ': 'Camera', 'つなぎ': 'Transition', '色ズレ': 'Color offset',
    'ズレ色A': 'Offset A', 'ズレ色B': 'Offset B', 'アクセント': 'Accent',
    '文字': 'Text', '補助': 'Secondary', '背景': 'Background',
    'グリッチ': 'Glitch', '質感': 'Texture',
    'この行の構成をロック': 'Lock this line', 'この行を再抽選': 'Reroll this line',
    'レイアウト指定': 'Choose layout', '開始（秒）': 'Start (s)',
    '・手動': ' · manual', '・自動': ' · automatic', '行目の開始秒': ' start time (s)',
    '行 / ': ' lines / ', 'カット': 'cuts', '行': 'line ',
    '自動': 'Auto', 'なし': 'None', 'カスタム': 'Custom',
    'ランダム': 'Random', '案目': 'variation', 'おまかせ：': 'Randomized: ',
    '配色：アクセント・ズレ色A/Bを変更': 'Palette: changed accent and offset colors',
    '構成：レイアウトと動きを再抽選': 'Arrangement: rerolled layout and motion',
    ' 種': ' types', '・': ' · ',
    'すべてON': 'All on', 'すべてOFF': 'All off', '反転': 'Invert',
    '（追加分がオフのため、おまかせでは選ばれません）': ' (new effects disabled for automatic picks)',
    '（和風の演出がオフのため、おまかせでは選ばれません）': ' (Japanese motifs disabled for automatic picks)',
    '（追加分がオフのため、自動では選ばれません）': ' (new effects disabled for automatic picks)',
    '（和風の演出がオフのため、自動では選ばれません）': ' (Japanese motifs disabled for automatic picks)',
    'グリーンバック': 'Green screen', 'ブラックバック': 'Black background',
    '白い文字と演出だけ': 'white text and effects only',
    '通常（スタイルの配色）': 'Style colors',
    'このブラウザは MP4 書き出しに対応していません（Chrome / Edge 推奨）': 'MP4 export is unavailable here (Chrome or Edge recommended)',
    'このブラウザでは ': 'This browser exports with ',
    '書き出し中はタブを開いたままにしてください。': 'Keep this tab open during export.',
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome / Edge の最新版で開くか、連番PNGを使ってください。': 'Video encoding (WebCodecs) is unavailable here. Try the latest Chrome or Edge, or export a PNG sequence.',
    '準備中…': 'Preparing…', '完成 ': 'Done: ', '秒': 's',
    '（保存はキャンセルされました）': ' (save canceled)', 'エラー: ': 'Error: ',
    '追加分の演出：使わない（最初の公開版の演出だけ）': 'New effects: off (original set only)',
    '追加分の演出：使う': 'New effects: on',
    '和風の演出：使わない（おまかせ・シャッフルで選ばれません）': 'Japanese motifs: off for random picks',
    '和風の演出：使う': 'Japanese motifs: on',
    'フォントを読み込めませんでした': 'Could not load the font',
    'プロジェクトを読み込めませんでした': 'Could not open the project',
    '解析中…': 'Analyzing audio…', '読み込めませんでした: ': 'Could not load: ',
    '約': 'about ', '（PC）': ' (installed)',
    '字面': 'JIZURA', '追加': 'New', '和': 'JP',
}

EXPORT = {
    '動画の編集情報を読み込めません。動画を読み込み直してください。': 'Could not read the video edits. Reimport the videos.',
    '動画「${name}」を再選択してください。元ファイルが読み込まれていません。': 'Reimport “${name}”. The source file is missing.',
    '動画「${source.name || clip.source && clip.source.name || clip.sourceId}」の音声を取得できません。このクリップを消音にするか、音楽ファイルを選んでください。': 'Could not read audio from “${source.name || clip.source && clip.source.name || clip.sourceId}”. Mute this clip or select an imported audio file.',
    '書き出す動画の長さを確認してください。': 'Check the duration of the video to export.',
    '編集した動画音声': 'Edited video audio',
    '編集した音声を準備中': 'Preparing edited audio',
    '音声を準備中': 'Preparing audio',
    'PNG画像を作成できませんでした。出力解像度を下げて再試行してください。': 'Could not create the PNG image. Lower the output resolution and try again.',
    'エンコーダーが停止しました。もう一度書き出してください。': 'The encoder stopped. Please export again.',
    'このブラウザでは音声付きMP4を書き出せません。Chrome / Edge で開くか、「音声を含める」をオフにしてください。': 'This browser cannot export MP4 with audio. Open in Chrome or Edge, or disable Include audio in video.',
    '書き出し用の描画領域を作成できませんでした。': 'Could not create the export canvas.',
    'このブラウザは動画エンコード（WebCodecs）に対応していません。Chrome か Edge の最新版で開いてください。': 'Video encoding (WebCodecs) is unavailable. Open in the latest Chrome or Edge.',
    'キャンセルしました': 'Canceled', 'フレーム ': 'Frame ',
    '音声をエンコード中': 'Encoding audio', '完了': 'Done',
}

MEDIA = {
    'キャンセルしました': 'Canceled',
    '動画をデコードできませんでした。別の形式で保存して読み込んでください。': 'Could not decode this video. Save it in another format and import it again.',
    'このブラウザでは動画の形式を再生できません。MP4（H.264）などに変換して読み込んでください。': 'This browser cannot play this video format. Convert it to a supported format such as H.264 MP4 and import it again.',
    '動画を読み込めませんでした。ファイルを確認してください。': 'Could not load the video. Please check the file.',
    '動画ファイルを選んでください。': 'Select a video file.',
    '動画の長さを取得できませんでした。動画編集ソフトなどで保存し直して読み込んでください。': 'Could not determine the video duration. Save it again with a video editor and reimport it.',
    '動画の読み込みがタイムアウトしました。ファイルの形式を確認してください。': 'Video loading timed out. Check the file format.',
    '動画の読み込みが完了していません。': 'The video has not finished loading.',
    '動画のフレーム取得がタイムアウトしました。別の形式で保存してお試しください。': 'Retrieving a video frame timed out. Try saving the video in another format.',
}

VIDEO_EDIT = {
    '編集するクリップが見つかりません。タイムラインから選び直してください。': 'Could not find the clip to edit. Select it again on the timeline.',
    '分割位置をクリップの内側へ動かしてください。分割後の両側に元動画の0.04秒以上が必要です。': 'Move the split point inside the clip. Each side needs at least 0.04 seconds of source footage.',
    "'動画'": "'Video'",
}

AE_UI = {
    '歌詞の言語': 'Lyrics language', "['自動判定', '日本語',": "['Auto-detect', '日本語',",
    '中国語（繁体字・簡体字）や韓国語の歌詞は、その文字を持つ書体で組みます（各スタイルの書体の雰囲気に近いものに置き換え）。自動判定はかな・ハングル・繁体字／簡体字に特有の字から判断します': 'Chinese (Traditional / Simplified) and Korean lyrics are set in fonts that have those characters, close in feel to each style. Auto-detect looks at kana, Hangul and the characters that differ between Traditional and Simplified Chinese.',
    "var JZ_SAMPLE = '夜明けの色を/覚えてる\\nほどけた声が遠くで鳴った\\nねえ、まだ間に合うかな\\n*透明*なままじゃ終われない!';": "var JZ_SAMPLE = 'I remember/the color of dawn\\nA voice faded into the distance\\nCan we still make it in time?\\n*Transparent* is not how this ends!';",
    'JIZURA 字面  lyric motion': 'JIZURA  lyric motion',
    '（': ' (', '）': ')', '部品': 'techniques',
    '歌詞（1行=1フレーズ　/ 区切り　*強調*　行末! インパクト）': 'One phrase per line. / = cut, *word* = emphasis, final ! = impact',
    'おまかせで生成（押すたびに別の演出）': 'Create a variation',
    'スタイル・雰囲気・演出の強さ・配色・シードをまるごとランダムに決めて、新しいコンポを作ります': 'Randomize style, mood, effects, colors and seed, then create a composition.',
    'オフのときは最初の公開版の演出（356部品・スタイル12種）だけを使います。オンにすると、あとから追加した演出・スタイル・書体も候補になります': 'Include techniques, styles and fonts added after the first release in random picks.',
    '提灯・はがき・障子・扇・家紋・青海波・桜の花びらなどの和風グラフィックと、和風のスタイル。オフにすると自動では選ばれません（追加分の判定のあとに適用）': 'Include Japanese motifs such as lanterns, shoji, fans and cherry blossoms in automatic picks.',
    'アクティブなコンポと同じ': 'Same as active comp',
    '通常（スタイルの背景）': 'Style background', 'グリーンバック（合成用）': 'Green screen (compositing)',
    'ブラックバック（合成用）': 'Black background (compositing)',
    'グリーンバック／ブラックバック：白い文字と演出だけを単色の背景の上に作ります（背景の模様・紙・粒子・周辺減光なし）。グリーンはキーイング、ブラックはスクリーン合成で抜けます': 'Solid green or black background behind white text and effects. Key out green or use Screen blending for black.',
    '自動（文字数・BPM から） / LRCの時刻': 'Auto (text length and BPM) / LRC timestamps',
    '選択レイヤーのマーカーを行頭に使う': 'Use selected layer markers for line starts',
    'コンポマーカーを行頭に使う': 'Use composition markers for line starts',
    '選択中の音声レイヤーを新しいコンポに入れる': 'Include selected audio layer in new composition',
    '標準（すべての手法を使う）': 'Standard (all techniques)',
    '雰囲気ごとに使うレイアウト・登場・退場の手法が絞られます（シードで再現）': 'Mood influences the selection of layouts, entrances and exits (reproducible by seed).',
    '背景に合うアクセント色とズレ色A/Bをランダムに選びます（明るさは背景に合わせて自動調整）': 'Randomize accent and offset colors with automatic brightness adjustment.',
    '配色を変更しました — 「コンポを生成する」で反映されます': 'Palette changed. Create a composition to apply it.',
    'ブラウザ版 JIZURA の「AE用に書き出し」で作った .json を読み込み、': 'Import a JSON file made with Export for AE in the browser app.',
    '同じタイミング・レイアウト・演出で編集可能なコンポを組みます。': 'Create an editable composition with the same timing, layouts and effects.',
    '思ったとおりにできないときは、下のボタンで診断レポート（JIZURA_report.txt）を保存して送ってください。': 'If the result looks wrong, save a diagnostic report (JIZURA_report.txt).',
    '診断レポートを保存（最後に作ったコンポ）': 'Save diagnostics for last composition',
    'PostScript名で指定（見つからない指定はここに落ちます）': 'Specify PostScript font names (fallbacks when a font is unavailable).',
    '常にこの4書体を使う（自動選択しない）': 'Always use these four fonts (disable automatic selection)',
    '選択中のテキストレイヤーの書体を「見出し」に': 'Use selected text layer font for display text',
    'Noto Sans JP / Noto Serif JP / Dela Gothic One などが入っていれば自動で使います（AE 2024以降）。': 'Installed Google Fonts are used automatically in After Effects 2024 or later.',
    'この PC に無い書体: ': 'Fonts missing on this computer: ',
    'JIZURA：次の書体がこの PC に無いため、近い書体で作りました。': 'JIZURA: These fonts are unavailable, so similar fonts were used.',
    'どれも Google Fonts（fonts.google.com）から無料で入れられます。入れて After Effects を再起動し、作り直すと、ブラウザ版と同じ書体になります。': 'Install them from Google Fonts, restart After Effects and rebuild for the closest browser match.',
    'JIZURA：この After Effects では書体が入っているかを確認できないため（AE 2024 より前）、「フォント」タブで指定した書体で作りました。': 'JIZURA: This version of After Effects cannot check installed fonts, so the font tab fallbacks were used.',
    'ブラウザ版と同じ書体にするには、使われている書体（Google Fonts）を入れて「フォント」タブで指定するか、AE 2024 以降で作ってください。': 'For matching type, install the Google Fonts used in the browser and select them in the font tab, or use AE 2024 or later.',
    'JIZURA：生成しましたが、一部に注意があります：': 'JIZURA: Composition created with some warnings:',
    'マーカーを使うには、コンポを開いてください': 'Open a composition to use markers',
    'マーカーのあるレイヤーを選択してください': 'Select a layer with markers',
    'マーカーが見つかりません': 'No markers found', 'マーカーを読めませんでした: ': 'Could not read markers: ',
    '構成の計算でエラー: ': 'Could not plan composition: ',
    '配色の値が読めないため、スタイルの色のままにしました（#RRGGBB 形式で入力）': 'Invalid color. Style colors were kept (enter #RRGGBB).',
    'JSONを読めませんでした: ': 'Could not read JSON: ',
    'JIZURA の AE用JSON ではないようです': 'This is not a JIZURA AE project JSON',
    'このパネルに無い表現 ': 'Techniques unavailable in this panel: ',
    'JIZURA：この JSON には、このパネルが作れない表現が ': 'JIZURA: This JSON contains ',
    ' 箇所あり、近い表現に置き換えました。': ' unsupported techniques; similar ones were substituted.',
    ' 箇所を、近い表現で作りました': ' instances were replaced by similar techniques',
    'ブラウザ版より古いパネルを使っている可能性があります。最新の JIZURA_AE.jsx（v': 'This panel may be older than the browser edition. Install the latest JIZURA_AE_en.jsx (v',
    '・707 部品）に差し替えて、After Effects を再起動してください。': ', 707 techniques) and restart After Effects.',
    '先にコンポを作ってください（このパネルで最後に作ったコンポを調べます）': 'Create a composition first; diagnostics inspect the last one created here.',
    '最後に作ったコンポが見つかりません（削除された可能性があります）': 'The last composition could not be found (it may have been deleted).',
    '診断中…（数十秒かかることがあります）': 'Diagnosing… (this can take a few seconds)',
    'レポートを保存しました：': 'Report saved: ',
    'レポートを保存できませんでした（環境設定 → スクリプトとエクスプレッション →「スクリプトによるファイルへの書き込みとネットワークへのアクセスを許可」をオンにしてください）。': 'Could not save report. Allow scripts to write files and access the network in After Effects preferences.',
    'テキストレイヤーを選択してください': 'Select a text layer', 'テキストレイヤーではありません': 'This is not a text layer',
    '追加分の演出も使う': 'Include new effects', '和風の演出も使う': 'Include Japanese motifs',
    '選択中の音声レイヤーも入れる': 'Include selected audio layer',
    'JSONを選んで生成…': 'Open JSON and build…',
    'スタイルの色を上書き': 'Override style colors', 'ランダム配色': 'Random palette',
    'コンポを生成する': 'Create composition', 'JSONから': 'From JSON', '歌詞から': 'From lyrics',
    'おまかせ：': 'Variation: ', 'ランダム配色': 'Random palette',
    '生成中…': 'Building…', '生成中にエラー: ': 'Build error: ',
    '診断：エクスプレッションのエラー ': 'Diagnostics: expression errors ',
    'JIZURA 診断：エクスプレッション ': 'JIZURA diagnostics: expressions ',
    ' 個のうち、エラー ': ', errors ', ' 個': '',
    '（時間の上限で途中まで）': ' (partial, time limit)', '（途中まで）': ' (partial)',
    '置換あり': 'Substitutions', '注意 ': 'Warnings: ', '件': '',
    '書体の代用 ': 'Font substitutions: ', '箇所': ' instances',
    '歌詞が空です': 'Lyrics are empty', '準備OK': 'Ready',
    '曲名': 'Song title', 'アーティスト': 'Artist', 'スタイル': 'Style',
    'サイズ': 'Size', '背景': 'Background', 'タイミング': 'Timing',
    '行の長さ': 'Line duration', '演出': 'Effects', '雰囲気': 'Mood',
    '動きの強さ': 'Motion strength', 'グリッチ': 'Glitch', '色ズレ': 'Color offset',
    '装飾の量': 'Decoration amount', 'カットの細かさ': 'Cut density',
    '質感': 'Texture', '背景の切替': 'Background changes',
    '2コマ打ち': 'On twos', 'フラッシュ': 'Flash',
    'スタイル次第': 'Auto by style', '非表示': 'Hide', '表示': 'Show',
    'シード': 'Seed', 'シャッフル': 'Shuffle',
    'アクセント・ズレ色': 'Accent and offset colors', 'アクセント': 'Accent',
    'ズレ色A': 'Offset A', 'ズレ色B': 'Offset B',
    'フォント': 'Fonts', '見出し': 'Display', '明朝': 'Serif',
    '小さな文字': 'Small text', '等幅': 'Monospace', '・': ' · ',
    '追加': 'New', '和': 'JP',
}

CEP = {
    '「${r.name}」を作成しました': 'Created “${r.name}”',
    'AE の「${r.name}」で拍を合わせました': 'Synced beats to “${r.name}” in AE',
    '曲（<span class="ae-audio-name"></span>）をコンポに入れる': 'Include audio (<span class="ae-audio-name"></span>) in composition',
    ' に接続しました': ' connected',
    'After Effects に接続中…（初回は数秒かかります）': 'Connecting to After Effects…',
    'After Effects に接続しました': 'connected to After Effects',
    'After Effects に接続できませんでした: ': 'Could not connect to After Effects: ',
    'After Effects に接続できませんでした': 'Could not connect to After Effects',
    'この PC に無い書体（': 'Fonts missing on this computer (',
    '）は近い書体で作りました。Google Fonts から入れて AE を再起動すると、同じ書体になります': ') were replaced with similar fonts. Install them from Google Fonts and restart AE for a closer match.',
    'この AE（2024 より前）では書体の有無を確認できないため、スクリプト版パネルの「フォント」タブの書体（未設定なら游ゴシック・游明朝）で作りました': 'AE before 2024 cannot detect installed fonts; ScriptUI font settings or system fallbacks were used.',
    'レポートを保存できませんでした（AE の環境設定「スクリプトによるファイルへの書き込み…を許可」をオンに）': 'Could not save report. Enable script file writing in AE preferences.',
    'このパネルでは曲ファイルを直接読めません。「曲を読み込む」から選んでください': 'This panel cannot read audio directly. Use Import audio instead.',
    'この曲ファイルは読み込めませんでした（wav / mp3 / m4a などを使ってください）': 'Could not read this audio file. Try WAV, MP3 or M4A.',
    '最後に作ったコンポを調べて JIZURA_report.txt を保存します（うまく作れないときに送ってください）': 'Check the last composition and save a JIZURA_report.txt diagnostic file.',
    'AE で選択している曲のレイヤーを読み込み、拍に合わせます（コンポを作るときにその曲も入ります）': 'Import the selected AE audio layer, analyze beats and include it in the composition.',
    '選択レイヤー（無ければコンポ）のマーカーを、各行の開始時刻にします': 'Use selected layer markers (or composition markers) for line start times.',
    '今の構成で After Effects にコンポを作ります': 'Build an After Effects composition from this arrangement.',
    '診断中…（数十秒かかることがあります）': 'Diagnosing… (this may take a few seconds)',
    'コンポを作成中…': 'Building composition…',
    'AEで選択中の曲': 'Selected AE audio',
    'AEのマーカーを行頭に': 'Use AE markers for lines',
    'AEでコンポを生成': 'Build in AE',
    'After Effects にコンポを作る': 'Build composition in After Effects',
    'After Effects にコンポを作成しました': 'Composition created in After Effects',
    '診断レポートを保存': 'Save diagnostic report',
    'コンポに入れる': 'include in composition',
    '作成できませんでした: ': 'Could not create composition: ',
    '作成できませんでした': 'Could not create composition',
    '近い表現で置換 ': 'Substitutions: ', '注意 ': 'Warnings: ',
    '診断：エクスプレッション ': 'Diagnostics: expressions ',
    ' 個のうちエラー ': ', errors ', ' 個': '', '（途中まで）': ' (partial)',
    '曲ファイルを読めませんでした: ': 'Could not read audio: ',
    'この曲ファイルは読み込めませんでした': 'Could not read this audio file',
    'のマーカー ': ' markers: ', ' 個を行の開始時刻にしました': ' line start times set',
    'レイヤー': 'Layer', 'コンポ': 'Composition',
    '（残り ': ' (remaining ', ' 行は自動）': ' lines automatic)',
    '動画・画像': 'Video and images',
    '保存しました: ': 'Saved: ', '保存': 'Save',
    ' カット': ' cuts', ' 秒': ' s', '曲入り': 'with audio',
    ' 箇所': ' instances', ' 件': ' items', 'レポート: ': 'Report: ',
    '「': '“', '」': '”', '（': ' (', '）': ')', '・': ' · ',
}

CEP_HOST = {
    'JIZURA の構成データではありません': 'This is not JIZURA project data',
    'コンポを開いて、曲のレイヤーを選択してください': 'Open a composition and select an audio layer',
    '曲（音声ファイル）のレイヤーを選択してください': 'Select an audio file layer',
    'コンポを開いてください': 'Open a composition',
    'マーカーが見つかりません（曲のレイヤーかコンポにマーカーを打ってください）': 'No markers found. Add markers to the audio layer or composition.',
    '構成データの一時ファイルが見つかりません': 'Temporary project data file not found',
    '先にこのパネルでコンポを作ってください': 'Create a composition in this panel first',
}


def localize_cep(source, host=False):
    return replace_copy(source, CEP_HOST if host else CEP)


def localize_ae(source):
    return (replace_copy(source, AE_UI)
            .replace('lyr.preferredSize = [340, 150]', 'lyr.preferredSize = [440, 150]')
            .replace('preferredSize.width = 86', 'preferredSize.width = 120')
            .replace('preferredSize.width = 70', 'preferredSize.width = 95'))


def replace_copy(source, glossary):
    # Longest first protects complete phrases from shorter label replacements.
    for japanese, english in sorted(glossary.items(), key=lambda pair: -len(pair[0])):
        source = source.replace(japanese, english)
    return source


def localize_body(source):
    return replace_copy(source, BODY).replace('You own the<strong>', 'You own the <strong>')


def localize_js(source, filename):
    if filename.endswith('12_ui.js'):
        return replace_copy(source, UI)
    if filename.endswith('11_export.js'):
        return replace_copy(source, EXPORT)
    if filename.endswith('10_video.js'):
        return replace_copy(source, MEDIA)
    if filename.endswith('10a_edit.js'):
        return replace_copy(source, VIDEO_EDIT)
    return source
